# Config file for the pyspark-stock-analytics application kafka producer
finnhub:
  symbols:
    - AAPL
    - AMZN
    - BINANCE:BTCUSDT
    - OANDA:EUR_USD
kafka:
  client_id: trades_analytics
  topic: trades