# Config file for the pyspark-stock-analytics application kafka producer
finnhub:
  symbols:
    - AAPL
    - AMZN
    - BINANCE:BTCUSDT
    - IC MARKETS:1
  kafka:
    client_id: trades_analytics
    topic: trades
    key: